
linters:
  enable:
    - cyclop
    - revive
    - govet
    - gocritic

linters-settings:
  cyclop:
    max-complexity: 20
  govet:
    check-shadowing: true
  gocritic:
      enabled-tags:
        - opinionated
