openapi: 3.0.0
info:
  title: Example API
  version: 1.0.0
paths:
  "/user/{user_id}":
    get:
      tags:
        - user
      operationId: getUser
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
            format: uint64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: "Invalid argument"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /users:
    post:
      tags:
        - user
      operationId: createUser
      responses:
        '201':
          description: "Created"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Created'
        '400':
          description: "Invalid argument"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: "Unknown"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  description: name
                  minLength: 1
                  maxLength: 100
                  type: string
                  example: "gami"
              required:
                - name
components:
  schemas:
    Created:
      type: object
      required:
        - id
        - message
      properties:
        id:
          type: integer
          format: uint64
          example: 1
        message:
          type: string
          example: "OK"
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: "Invalid Argument"
    User:
      type: object
      required:
        - id
        - name
        - profile
      properties:
        id:
          type: integer
          format: uint64
          description: identifier
          example: 1
        name:
          type: string
          description: name
          example: gami
        profile:
          $ref: '#/components/schemas/Error'
    Profile:
      type: object
      required:
        - description
      properties:
        description:
          type: string
          description: description
          example: Hello
