version: "3"

services:
  app:
    build: local/
    tty: true
    env_file:
      - ./env/db.env
    volumes:
      - "..:/app"
    links:
      - db
      - db_test
      - localstack
      - localstack_test
    command: make dev
    networks:
      - local_network
  localstack:
    image: localstack/localstack
    environment:
      - HOSTNAME_EXTERNAL=localstack
    ports:
      - '4576:4576'
  localstack_test:
    image: localstack/localstack
    environment:
      - HOSTNAME_EXTERNAL=localstack_test
    ports:
      - '4577:4576'
  db_test:
    image: mysql:5.7
    platform: linux/x86_64
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: "user_test"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
    command: mysqld --innodb-file-format=Barracuda --innodb-file-format-max=Barracuda --innodb-file-per-table=true --innodb-large-prefix=true
    networks:
      - local_network
  db:
    image: mysql:5.7
    platform: linux/x86_64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: "user"
      MYSQL_USER: "dev"
      MYSQL_PASSWORD: "dev"
    command: mysqld --innodb-file-format=Barracuda --innodb-file-format-max=Barracuda --innodb-file-per-table=true --innodb-large-prefix=true
    networks:
      - local_network
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8083:8080"
    volumes:
      - ../resources/openapi/openapi.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml
    networks:
      - local_network
networks:
  local_network:
    driver: bridge
